baseURL = "https://example.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "地铁上的耳机"
theme = "anubis"
paginate = 3

disqusShortname = ""
googleAnalytics = ""

[author]
name = "happyhah"

[params]
author = "happyhah"
description = "记录与分享."
dateFormat = "2023-03-22"
paginationSinglePost = true
style = "auto"
readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
locale = "cn-zh"

# Graphcomment support
graphcommentId = ""

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional
  
[[params.social]]
id = "docs"
url = "https://gohugo.io/documentation/"

[[params.social]]
id = "github"
url = "https://github.com/mitrichius/hugo-theme-anubis"

[languages.cn]
languageName = "Chinese"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 3

[languages.en]
languageName = "english"

[[languages.en.menu.main]]
identifier = "about"
name = "O Hugo"
url = "/about/"
weight = 1

[[languages.en.menu.main]]
identifier = "tags"
name = "Tagi"
url = "/tags/"
weight = 2

[[languages.en.menu.main]]
identifier = "archive"
name = "Archiwum"
url = "/posts/"
weight = 3

[[languages.en.params]]
locale = "en-US"

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
