baseURL = ""
languageCode = "zh-cn"
title = "地铁上的耳机"
theme = "乐天style"
paginate = 10

disqusShortname = ""
googleAnalytics = ""

[author]
name = "Happyhah"

[params]
author = "Happyhah"
avatar = "/images/me.jpg"
description = "记录与分享"
dateFormat = "2023-03-24"
paginationSinglePost = true
style = "auto"
readMore = true
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true

# Graphcomment support
graphcommentId = ""

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional

[[params.social]]
id = "docs"
url = "https://gohugo.io/documentation/"

[[params.social]]
id = "github"
url = "https://github.com/mitrichius/hugo-theme-anubis"

[menu]

[[menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 3

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 2

[[menu.main]]
name = "文章"
identifier = "archive"
url = "/posts/"
weight = 1

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true