languageCode = "zh"
baseUrl = ""
title = "地铁上的耳机"
theme = "anubis"
paginate = 10
disqusShortname = "yourdiscussshortname"
googleAnalytics = "G-12345"
enableRobotsTXT = true

[[menu.main]]
identifier = "archive"
name = "Archive"
title = "Archive"
url = "/posts/"
weight = 0

[params]
author = "Happy"
email = "mail@example.org"
avatar = "/images/me.png"
description = ""
dateFormat = "2023-03-22"
paginationSinglePost = true
style = "light-without-switcher"
readMore = false
readNextPosts = 5
disableSummary = false
copyCodeButton = true
rssAsSocialIcon = true
utterancesRepo = ""
utterancesTheme = ""
utterancesIssue = ""
utterancesLabel = ""
graphcommentId = ""

  [params.isso]
  enabled = true
  data = "https://comments.example.com/"
  jsLocation = "https://comments.example.com/js/embed.min.js"
  css = true
  lang = "de"
  replyToSelf = true
  requireAuthor = true
  requireEmail = true
  id = "thread-id"
  avatar = true
  avatar-bg = "#f0f0f0"
  feed = false

  [params.webmentions]
  url = "https://yourdomain.com/webemntions/receive"
  login = "hugo-theme-anubis"
  pingback = true

  [[params.social]]
  id = "github"
  name = "gohugoio"

[markup.goldmark.renderer]
unsafe = true
